left_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - left_joint_1
    - left_joint_2
    - left_joint_3
    - left_joint_4
    - left_joint_5
    - left_joint_6
  gains:
    left_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
right_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - right_joint_1
    - right_joint_2
    - right_joint_3
    - right_joint_4
    - right_joint_5
    - right_joint_6
  gains:
    right_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
dual_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - left_joint_1
    - left_joint_2
    - left_joint_3
    - left_joint_4
    - left_joint_5
    - left_joint_6
    - right_joint_1
    - right_joint_2
    - right_joint_3
    - right_joint_4
    - right_joint_5
    - right_joint_6
  gains:
    left_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
left_controller_gazebo:
  type: position_controllers/JointTrajectoryController
  joints:
    - left_joint_1
    - left_joint_2
    - left_joint_3
    - left_joint_4
    - left_joint_5
    - left_joint_6
  gains:
    left_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
right_controller_gazebo:
  type: position_controllers/JointTrajectoryController
  joints:
    - right_joint_1
    - right_joint_2
    - right_joint_3
    - right_joint_4
    - right_joint_5
    - right_joint_6
  gains:
    right_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
dual_controller_gazebo:
  type: position_controllers/JointTrajectoryController
  joints:
    - left_joint_1
    - left_joint_2
    - left_joint_3
    - left_joint_4
    - left_joint_5
    - left_joint_6
    - right_joint_1
    - right_joint_2
    - right_joint_3
    - right_joint_4
    - right_joint_5
    - right_joint_6
  gains:
    left_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1