; Auto-generated. Do not edit!


(cl:in-package openpose-msg)


;//! \htmlinclude anglegoalFeedback.msg.html

(cl:defclass <anglegoalFeedback> (roslisp-msg-protocol:ros-message)
  ((error
    :reader error
    :initarg :error
    :type sensor_msgs-msg:JointState
    :initform (cl:make-instance 'sensor_msgs-msg:JointState)))
)

(cl:defclass anglegoalFeedback (<anglegoalFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <anglegoalFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'anglegoalFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name openpose-msg:<anglegoalFeedback> is deprecated: use openpose-msg:anglegoalFeedback instead.")))

(cl:ensure-generic-function 'error-val :lambda-list '(m))
(cl:defmethod error-val ((m <anglegoalFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader openpose-msg:error-val is deprecated.  Use openpose-msg:error instead.")
  (error m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <anglegoalFeedback>) ostream)
  "Serializes a message object of type '<anglegoalFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'error) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <anglegoalFeedback>) istream)
  "Deserializes a message object of type '<anglegoalFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'error) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<anglegoalFeedback>)))
  "Returns string type for a message object of type '<anglegoalFeedback>"
  "openpose/anglegoalFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'anglegoalFeedback)))
  "Returns string type for a message object of type 'anglegoalFeedback"
  "openpose/anglegoalFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<anglegoalFeedback>)))
  "Returns md5sum for a message object of type '<anglegoalFeedback>"
  "e2493ab760fcc1a7a80910d9ebc59fbe")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'anglegoalFeedback)))
  "Returns md5sum for a message object of type 'anglegoalFeedback"
  "e2493ab760fcc1a7a80910d9ebc59fbe")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<anglegoalFeedback>)))
  "Returns full string definition for message of type '<anglegoalFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Define the feedback~%~%sensor_msgs/JointState error~%~%================================================================================~%MSG: sensor_msgs/JointState~%# This is a message that holds data to describe the state of a set of torque controlled joints. ~%#~%# The state of each joint (revolute or prismatic) is defined by:~%#  * the position of the joint (rad or m),~%#  * the velocity of the joint (rad/s or m/s) and ~%#  * the effort that is applied in the joint (Nm or N).~%#~%# Each joint is uniquely identified by its name~%# The header specifies the time at which the joint states were recorded. All the joint states~%# in one message have to be recorded at the same time.~%#~%# This message consists of a multiple arrays, one for each part of the joint state. ~%# The goal is to make each of the fields optional. When e.g. your joints have no~%# effort associated with them, you can leave the effort array empty. ~%#~%# All arrays in this message should have the same size, or be empty.~%# This is the only way to uniquely associate the joint name with the correct~%# states.~%~%~%Header header~%~%string[] name~%float64[] position~%float64[] velocity~%float64[] effort~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'anglegoalFeedback)))
  "Returns full string definition for message of type 'anglegoalFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Define the feedback~%~%sensor_msgs/JointState error~%~%================================================================================~%MSG: sensor_msgs/JointState~%# This is a message that holds data to describe the state of a set of torque controlled joints. ~%#~%# The state of each joint (revolute or prismatic) is defined by:~%#  * the position of the joint (rad or m),~%#  * the velocity of the joint (rad/s or m/s) and ~%#  * the effort that is applied in the joint (Nm or N).~%#~%# Each joint is uniquely identified by its name~%# The header specifies the time at which the joint states were recorded. All the joint states~%# in one message have to be recorded at the same time.~%#~%# This message consists of a multiple arrays, one for each part of the joint state. ~%# The goal is to make each of the fields optional. When e.g. your joints have no~%# effort associated with them, you can leave the effort array empty. ~%#~%# All arrays in this message should have the same size, or be empty.~%# This is the only way to uniquely associate the joint name with the correct~%# states.~%~%~%Header header~%~%string[] name~%float64[] position~%float64[] velocity~%float64[] effort~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <anglegoalFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'error))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <anglegoalFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'anglegoalFeedback
    (cl:cons ':error (error msg))
))
