#!/usr/bin/env python
# -*- coding: utf-8 -*-

import socket
import time
import json

class openpose_client:
	
	def client_init(self):
		self.tcp_client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
		self.tcp_client_socket.connect( ('219.228.121.4', 6666) )
		print('connect to the server')

	def get_json_data(self):
		self.tcp_client_socket.send('connecting'.encode("utf-8"))
		receive_data_json = self.tcp_client_socket.recv(10240)
		receive_data_dict = json.loads(receive_data_json)
		print(receive_data_dict['people'][0]['pose_keypoints_3d'])
		time.sleep(1)

if __name__ == "__main__":
	robot_client = openpose_client()
	robot_client.client_init()
	while True:
		robot_client.get_json_data()
		pass