controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - right_joint_1
      - right_joint_2
      - right_joint_3
      - right_joint_4
      - right_joint_5
      - right_joint_6
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses per group
#  - group: arm
#    pose: home

  []