// Generated by gencpp from file openpose/anglegoalGoal.msg
// DO NOT EDIT!


#ifndef OPENPOSE_MESSAGE_ANGLEGOALGOAL_H
#define OPENPOSE_MESSAGE_ANGLEGOALGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/JointState.h>

namespace openpose
{
template <class ContainerAllocator>
struct anglegoalGoal_
{
  typedef anglegoalGoal_<ContainerAllocator> Type;

  anglegoalGoal_()
    : jointstate()  {
    }
  anglegoalGoal_(const ContainerAllocator& _alloc)
    : jointstate(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::JointState_<ContainerAllocator>  _jointstate_type;
  _jointstate_type jointstate;




  typedef boost::shared_ptr< ::openpose::anglegoalGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openpose::anglegoalGoal_<ContainerAllocator> const> ConstPtr;

}; // struct anglegoalGoal_

typedef ::openpose::anglegoalGoal_<std::allocator<void> > anglegoalGoal;

typedef boost::shared_ptr< ::openpose::anglegoalGoal > anglegoalGoalPtr;
typedef boost::shared_ptr< ::openpose::anglegoalGoal const> anglegoalGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openpose::anglegoalGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openpose::anglegoalGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace openpose

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'openpose': ['/home/pn/openpose_ws/devel/share/openpose/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::openpose::anglegoalGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openpose::anglegoalGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpose::anglegoalGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpose::anglegoalGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpose::anglegoalGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpose::anglegoalGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openpose::anglegoalGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a4eea410e374809eb9cf3036acbb3c94";
  }

  static const char* value(const ::openpose::anglegoalGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa4eea410e374809eULL;
  static const uint64_t static_value2 = 0xb9cf3036acbb3c94ULL;
};

template<class ContainerAllocator>
struct DataType< ::openpose::anglegoalGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openpose/anglegoalGoal";
  }

  static const char* value(const ::openpose::anglegoalGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openpose::anglegoalGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#Define the goal \n\
sensor_msgs/JointState jointstate\n\
\n\
\n\
================================================================================\n\
MSG: sensor_msgs/JointState\n\
# This is a message that holds data to describe the state of a set of torque controlled joints. \n\
#\n\
# The state of each joint (revolute or prismatic) is defined by:\n\
#  * the position of the joint (rad or m),\n\
#  * the velocity of the joint (rad/s or m/s) and \n\
#  * the effort that is applied in the joint (Nm or N).\n\
#\n\
# Each joint is uniquely identified by its name\n\
# The header specifies the time at which the joint states were recorded. All the joint states\n\
# in one message have to be recorded at the same time.\n\
#\n\
# This message consists of a multiple arrays, one for each part of the joint state. \n\
# The goal is to make each of the fields optional. When e.g. your joints have no\n\
# effort associated with them, you can leave the effort array empty. \n\
#\n\
# All arrays in this message should have the same size, or be empty.\n\
# This is the only way to uniquely associate the joint name with the correct\n\
# states.\n\
\n\
\n\
Header header\n\
\n\
string[] name\n\
float64[] position\n\
float64[] velocity\n\
float64[] effort\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::openpose::anglegoalGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openpose::anglegoalGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.jointstate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct anglegoalGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openpose::anglegoalGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openpose::anglegoalGoal_<ContainerAllocator>& v)
  {
    s << indent << "jointstate: ";
    s << std::endl;
    Printer< ::sensor_msgs::JointState_<ContainerAllocator> >::stream(s, indent + "  ", v.jointstate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENPOSE_MESSAGE_ANGLEGOALGOAL_H
