(cl:defpackage perception_neuron_one_topic_version-msg
  (:use )
  (:export
   "<ANGLEGOALACTION>"
   "ANGLEGOALACTION"
   "<ANGLEGOALACTIONGOAL>"
   "ANGLEGOALACTIONGOAL"
   "<ANGLEGOALACTIONFEEDBACK>"
   "ANGLEGOALACTIONFEEDBACK"
   "<ANGLEGOALGOAL>"
   "ANGLEGOALGOAL"
   "<ANGLEGOALACTIONRESULT>"
   "ANGLEGOALACTIONRESULT"
   "<ANGLEGOALFEEDBACK>"
   "ANGLEGOALFEEDBACK"
   "<ANGLEGOALRESULT>"
   "ANGLEGOALRESULT"
  ))

