; Auto-generated. Do not edit!


(cl:in-package perception_neuron_one_topic_version-msg)


;//! \htmlinclude anglegoalResult.msg.html

(cl:defclass <anglegoalResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass anglegoalResult (<anglegoalResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <anglegoalResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'anglegoalResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name perception_neuron_one_topic_version-msg:<anglegoalResult> is deprecated: use perception_neuron_one_topic_version-msg:anglegoalResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <anglegoalResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader perception_neuron_one_topic_version-msg:result-val is deprecated.  Use perception_neuron_one_topic_version-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <anglegoalResult>) ostream)
  "Serializes a message object of type '<anglegoalResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'result) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <anglegoalResult>) istream)
  "Deserializes a message object of type '<anglegoalResult>"
    (cl:setf (cl:slot-value msg 'result) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<anglegoalResult>)))
  "Returns string type for a message object of type '<anglegoalResult>"
  "perception_neuron_one_topic_version/anglegoalResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'anglegoalResult)))
  "Returns string type for a message object of type 'anglegoalResult"
  "perception_neuron_one_topic_version/anglegoalResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<anglegoalResult>)))
  "Returns md5sum for a message object of type '<anglegoalResult>"
  "eb13ac1f1354ccecb7941ee8fa2192e8")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'anglegoalResult)))
  "Returns md5sum for a message object of type 'anglegoalResult"
  "eb13ac1f1354ccecb7941ee8fa2192e8")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<anglegoalResult>)))
  "Returns full string definition for message of type '<anglegoalResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Define the result~%bool result~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'anglegoalResult)))
  "Returns full string definition for message of type 'anglegoalResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Define the result~%bool result~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <anglegoalResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <anglegoalResult>))
  "Converts a ROS message object to a list"
  (cl:list 'anglegoalResult
    (cl:cons ':result (result msg))
))
