; Auto-generated. Do not edit!


(cl:in-package perception_neuron_one_topic_version-msg)


;//! \htmlinclude anglegoalGoal.msg.html

(cl:defclass <anglegoalGoal> (roslisp-msg-protocol:ros-message)
  ((jointstate
    :reader jointstate
    :initarg :jointstate
    :type sensor_msgs-msg:JointState
    :initform (cl:make-instance 'sensor_msgs-msg:JointState)))
)

(cl:defclass anglegoalGoal (<anglegoalGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <anglegoalGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'anglegoalGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name perception_neuron_one_topic_version-msg:<anglegoalGoal> is deprecated: use perception_neuron_one_topic_version-msg:anglegoalGoal instead.")))

(cl:ensure-generic-function 'jointstate-val :lambda-list '(m))
(cl:defmethod jointstate-val ((m <anglegoalGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader perception_neuron_one_topic_version-msg:jointstate-val is deprecated.  Use perception_neuron_one_topic_version-msg:jointstate instead.")
  (jointstate m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <anglegoalGoal>) ostream)
  "Serializes a message object of type '<anglegoalGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'jointstate) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <anglegoalGoal>) istream)
  "Deserializes a message object of type '<anglegoalGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'jointstate) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<anglegoalGoal>)))
  "Returns string type for a message object of type '<anglegoalGoal>"
  "perception_neuron_one_topic_version/anglegoalGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'anglegoalGoal)))
  "Returns string type for a message object of type 'anglegoalGoal"
  "perception_neuron_one_topic_version/anglegoalGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<anglegoalGoal>)))
  "Returns md5sum for a message object of type '<anglegoalGoal>"
  "a4eea410e374809eb9cf3036acbb3c94")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'anglegoalGoal)))
  "Returns md5sum for a message object of type 'anglegoalGoal"
  "a4eea410e374809eb9cf3036acbb3c94")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<anglegoalGoal>)))
  "Returns full string definition for message of type '<anglegoalGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Define the goal ~%sensor_msgs/JointState jointstate~%~%~%================================================================================~%MSG: sensor_msgs/JointState~%# This is a message that holds data to describe the state of a set of torque controlled joints. ~%#~%# The state of each joint (revolute or prismatic) is defined by:~%#  * the position of the joint (rad or m),~%#  * the velocity of the joint (rad/s or m/s) and ~%#  * the effort that is applied in the joint (Nm or N).~%#~%# Each joint is uniquely identified by its name~%# The header specifies the time at which the joint states were recorded. All the joint states~%# in one message have to be recorded at the same time.~%#~%# This message consists of a multiple arrays, one for each part of the joint state. ~%# The goal is to make each of the fields optional. When e.g. your joints have no~%# effort associated with them, you can leave the effort array empty. ~%#~%# All arrays in this message should have the same size, or be empty.~%# This is the only way to uniquely associate the joint name with the correct~%# states.~%~%~%Header header~%~%string[] name~%float64[] position~%float64[] velocity~%float64[] effort~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'anglegoalGoal)))
  "Returns full string definition for message of type 'anglegoalGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Define the goal ~%sensor_msgs/JointState jointstate~%~%~%================================================================================~%MSG: sensor_msgs/JointState~%# This is a message that holds data to describe the state of a set of torque controlled joints. ~%#~%# The state of each joint (revolute or prismatic) is defined by:~%#  * the position of the joint (rad or m),~%#  * the velocity of the joint (rad/s or m/s) and ~%#  * the effort that is applied in the joint (Nm or N).~%#~%# Each joint is uniquely identified by its name~%# The header specifies the time at which the joint states were recorded. All the joint states~%# in one message have to be recorded at the same time.~%#~%# This message consists of a multiple arrays, one for each part of the joint state. ~%# The goal is to make each of the fields optional. When e.g. your joints have no~%# effort associated with them, you can leave the effort array empty. ~%#~%# All arrays in this message should have the same size, or be empty.~%# This is the only way to uniquely associate the joint name with the correct~%# states.~%~%~%Header header~%~%string[] name~%float64[] position~%float64[] velocity~%float64[] effort~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <anglegoalGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'jointstate))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <anglegoalGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'anglegoalGoal
    (cl:cons ':jointstate (jointstate msg))
))
